In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import time
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB, BernoulliNB, MultinomialNB

In [3]:
data = pd.read_csv('../data/container_matrix_test.csv', delimiter=",")
data.head()

,Timestamp,ID,Temperature(celsius),Target_Temperature(celsius),Amp,CumulativePowerConsumption,ContentType,Humidity,CO2,Door_Open,Maintainence_Required,Defrost_Cycle
0,2019-03-19 T16:05 Z,1463,5.551045,4.4,2.518416,8.943642,2,1.588056,8.679748,0,1,6
1,2019-03-19 T16:05 Z,1463,6.867771,4.4,2.647991,8.407460,4,9.710923,8.958477,0,1,6
2,2019-03-19 T16:20 Z,1463,3.647704,4.4,2.202307,9.628854,5,6.985099,5.283873,0,1,6
3,2019-03-19 T16:20 Z,1463,11.245505,4.4,1.629402,8.321084,4,20.236364,12.158607,0,1,6
4,2019-03-19 T16:35 Z,1463,4.582888,4.4,3.228984,7.806996,4,0.132568,20.620137,0,1,6

In [4]:
# create a Python list of feature names
feature_cols = ['Temperature(celsius)', 'Door_Open','Target_Temperature(celsius)','Amp','ContentType','CumulativePowerConsumption'
                          ,'Humidity','CO2','Defrost_Cycle']

# use the list to select a subset of the original DataFrame
X = data[feature_cols]
y = data['Maintainence_Required']

# print the first 5 rows
X.head()

,Temperature(celsius),Door_Open,Target_Temperature(celsius),Amp,ContentType,CumulativePowerConsumption,Humidity,CO2,Defrost_Cycle
0,5.551045,0,4.4,2.518416,2,8.943642,1.588056,8.679748,6
1,6.867771,0,4.4,2.647991,4,8.407460,9.710923,8.958477,6
2,3.647704,0,4.4,2.202307,5,9.628854,6.985099,5.283873,6
3,11.245505,0,4.4,1.629402,4,8.321084,20.236364,12.158607,6
4,4.582888,0,4.4,3.228984,4,7.806996,0.132568,20.620137,6

In [5]:
import pickle

#loading a model from a file called model.pkl
model = pickle.load(open("model_bays.pkl","r"))

In [6]:
# make predictions on the input set
y_pred = model.predict(X)
print y_pred
#y_pred.shape
print(np.sqrt(metrics.mean_squared_error(y, y_pred)))

[1 1 1 ... 1 1 1]
0.0